### ISSUE TITLE
Dependency resolution doesn't work with non v9 Angular

### ISSUE THREAD

**Issue by iamtheddrman** [becher/angular-device-information#5]
I'm on Angular 14.1.1 and when I try to npm install this package, I get an npm error that the dependency @angular/common@"^9.1.13" could not be resolved.

Similar packages that support multiple versions of Angular have been branched to release for specific versions of Angular, with any bug fixes from master being merged/cherry-picked out to the various Angular-version branches. Then, multiple versions of the package are released to npm, one for each targeted version of Angular.

Furthermore, it appears that for compatibility's sake, this is still a View Engine library. It would be great to get an Ivy distribution for the versions of Angular that support it. During an ng build, I get the following output:
`⠹ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:`
`- angular-device-information [es2015/esm2015] (git+https://github.com/becher/angular-device-information.git)`
`Encourage the library authors to publish an Ivy distribution.`

I'm not sure if that's too much work for this project, but figured it was worth a request. I can force the install for now and get it to work, but it's definitely not ideal since every developer on the team has to do the same.

**Comment by becher** [comment]
thank you for your message, i will work to fix it

**Comment by becher** [comment]
fixed
